### PR TITLE
Update self-venv on rye update

### LINKED ISSUE #859: 0.28.0 has ruff 0.2.2 when update
### Steps to Reproduce

```
export RYE_VERSION=0.27.0
export RYE_INSTALL_OPTION="--yes"
curl -sSf https://rye-up.com/get | bash
source "$HOME/.rye/env"
rye self update
~/.rye/self/bin/ruff --version
```

### Expected Result

```
ruff 0.3.0
```

### Actual Result

```
ruff 0.2.2
```

### Version Info

rye 0.28.0
commit: 0.28.0 (c44dc7ec8 2024-03-07)
platform: linux (aarch64)
self-python: cpython@3.12.2
symlink support: true
uv enabled: true

### Stacktrace

_No response_

### PR DESCRIPTION
**Pull request by mitsuhiko**
After update this will attempt to run `rye init` and the `python` shim in the context of that project. This under all known Rye versions should trigger a python only sync and updating of the internals.

Fixes #859

### CODE REVIEW

**Comment by monospacedmagic** [comment]
Just to clarify, doesn't `rye init` initialize a prohect at `.` if used outside of a project? I feel like that would be unintended behavior, no? Am I missing something?

**Comment by mitsuhiko** [comment]
@monospacedmagic it initializes a project in a temporary folder. This is the most portable way even when downgrading to trigger the update of the venv.

Future versions could gain a specific command to update the internal venv but since this should support downgrades too that’s not too helpful today.

**Comment by bluss** [comment]
One question I have, is it possible that pip-tools is never updated automatically - it looks that way from a few bugs reported here? It should hopefully be removed by uv soon, but still could be good to know for sure.

**Comment by mitsuhiko** [comment]
Yeah I think this might have regressed. It used to be that `pip-tools` was wiped together with the self venv on update:

https://github.com/astral-sh/rye/blob/f5525c985d7d35f635419083a0e46af0ed5eaf61/rye/src/bootstrap.rs#L82-L86

The current code does not do that:

https://github.com/astral-sh/rye/blob/71166f4c38711b9a07bab2a4a838eb3d46b24133/rye/src/bootstrap.rs#L108-L109

**Pull request merged**
