### PR TITLE
Implement `rye test` command built on pytest

### PR DESCRIPTION
**Pull request by hyyking**
## Overview:

Introducing the `rye test` command in Rye. The command would provide a similar experience to `cargo test`, built on top of pytest we get a known and extendable test framework. Users could utilize this unified command with the syntax `rye test [OPTIONS]` for a good default testing experience across rye managed projects.

I tried to follow the ruff implementation. Many things such as the pytest arguments need to be specified as the library is really extensive with its arguments.

## `rye test`:

- *Simplified Workflows:* Implement a unified testing process using the best available tools and promoting tests consistency accross workspaces.
- *Documentation Test:* As for `cargo test` using `doctest`/`pytest` or even [`jupyter-sphinx`](https://pypi.org/project/jupyter-sphinx/) this command _could_ also be able to run documentation tests.

## Why pytest:
- *Widespread Adoption:* Pytest is a widely adopted testing framework for small and larger open source projects such as django
- *Rich Assertions and Fixture System:* Provides expressive assertions (ex: with diff) and a fixture system (plugins).
- *Seamless Integration:* Pytest integrates with various IDEs and other development tools.

## Details

1. pytest needs to be installed in the package environment instead of rye's. This implementation currently works with the small example test I copied from `rye-devtools`.

2. pytest fixtures (ex: pytest-sugar, pytest-regressions) coming from external dependencies and workspaces will be shared in the currently single environment provided by rye.

## Unresolved Questions:

- [ ] Should tests environments be separate from rye's single env model to allow for per project test dependencies ?

Tested on the current project as well as this [scafold](https://github.com/hyyking/whynotrye/tree/master)

### CODE REVIEW

**Comment by hyyking** [comment]
@cnpryer @mitsuhiko Any thoughts on how to push this forward ? I can take a stab at implementing tox like sessions before if required.

**Comment by cnpryer** [comment]
> cnpryer mitsuhiko Any thoughts on how to push this forward ? I can take a stab at implementing tox like sessions before if required.

IMO your best bet is first establishing what a path to a `rye test` could look like. As a user of Rye, I'd love to have a `rye test` command, but I understand that testing in Python isn't necessarily standardized.

As a user/contributor (I'm not a maintainer of this project), here's how I'd probably approach requesting this feature:

1. I'd summarize what it is and how it could work
2. I'd summarize the value of something like this (why is it important to ship `rye test` specifically)
3. Then I'd probably research testing framework usage and share that as part of the request

**Comment by hyyking** [comment]
Alright thanks for the tips, this PR already implements a basic `rye test` functionality I'll think about how to better explain and document the idea more. As per test frameworks I don't see another contender as pytest has become the standard in most large open source python projects.

**Comment by cnpryer** [comment]
At the moment I am also of the opinion that pytest may be standard enough, but I'm just not entirely sure since it doesn't ship with the standard tooling.

Standards are helpful for this decision, but it's also not the entire picture. So for that reason alone I'd consider discussing this more before continuing.

**Comment by hyyking** [comment]
> At the moment I am also of the opinion that pytest may be standard enough, but I'm just not entirely sure since it doesn't ship with the standard tooling.

One of the strenghts of rye is opinionated defaults and pytest being a popular good choice makes it eligible in this sense.

> Standards are helpful for this decision, but it's also not the entire picture. So for that reason alone I'd consider discussing this more before continuing.

For sure, I have updated the PR message to add more context. If you have the time to try what is currently there I'd love to hear some usasge feedback, I've been using it myself and it seems to work fine for now.

**Comment by lleites** [comment]
Great work @hyyking ! I really like the UX of this too, IMHO this is the missing piece of rye to have a complete development cycle workflow. 
In what regards to using pytest or not, it is today a standard, like it or not, and the idea behind rye, as was already mentioned, is that it is opinionated.
I hope this PR gets into the radar of the team soon.

**Comment by mitsuhiko** [comment]
I will work on this based on this PR. I'm not entirely sure I like some of the implications of the elements of this but I think it's a good start.

**Comment by hyyking** [comment]
I thought you could, thanks !

**Pull request closed without merging**
